version: "3.9"

services:
  postgres:
    container_name: "postgres"
    image: postgres
    env_file:
      - .env
    ports:
      - "5433:5432"
    networks:
      - web
    volumes:
      - ./.data:/var/lib/postgresql/data

  api:
    container_name: "api"

    image: node:16
    build: ./api
    command: "npm run dev:api"
    ports:
      - "3030:3030"
    expose:
      - 3030
    volumes:
      - .:/srv/api
    env_file:
      - .env
    working_dir: /srv/api
    depends_on:
      - postgres
    networks:
      - web

networks:
  web:
    external: true
