version: "3.9"

services:
  postgres:
    container_name: "@home-inventory/postgres"
    image: postgres
    env_file:
      - .env
    ports:
      - "5433:5432"
    networks:
      - web
    volumes:
      - ./.data:/var/lib/postgresql/data

  redis:
    container_name: "@home-inventory/redis"
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    ports:
      - "6379:6379"
    networks:
      - web
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf

  api:
    container_name: "@home-inventory/api"

    image: node:16
    command: "yarn workspace @home-inventory/api start"
    ports:
      - "3030:3030"
    expose:
      - 3030
    volumes:
      - .:/srv/api
    env_file:
      - .env
    working_dir: /srv/api
    depends_on:
      - postgres
    networks:
      - web

  web:
    container_name: "@home-inventory/web"
    image: node:16
    command: "yarn workspace @home-inventory/web start"
    ports:
      - "3000:3000"
    expose:
      - 3000
    volumes:
      - .:/srv/web
    working_dir: /srv/web
    depends_on:
      - api
    networks:
      - web
    env_file:
      - .env

volumes:
  redis-data:
  redis-conf:

networks:
  web:
    external: true
