name: Check TS build (api)

on: [push, pull_request]

jobs:
  tsc-api:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --immutable
      - name: Generate Prisma types
        run: yarn workspace @home-inventory/api prisma generate
      - name: Run test-tsc
        run: yarn workspace @home-inventory/api test-tsc
